env: standard
runtime: nodejs16
instance_class: F2
service: default
inbound_services:
- warmup
automatic_scaling:
    min_idle_instances: 1
    min_instances: 1
handlers:
  - url: /.*
    secure: always
    script: auto
